### PR TITLE
Update of cypress tests + makefile fix

### PR DESCRIPTION
**Pull request by daniel-de-vera**
This PR updates the cypress tests against the latest version of the frontend.
E.g.:

```bash
$ ./signadot job submit -f  /home/ddv/git/signadot/hotrod/.signadot/ict/e2e-tests-job.yaml --set frontend_sandbox_name= --set location_sandbox_name= --set route_sandbox_name= --set driver_sandbox_name= --set sandbox= --set branch=update-cypress-test --set namespace=hotrod-devmesh --attach
Job hotrod-cypress-e2e-w7aq0xy queued on Job Runner Group: cypress

Dashboard page: https://app.signadot.com/testing/jobs/hotrod-cypress-e2e-w7aq0xy

Cloning signadot repo
Cloning into 'hotrod'...
[STARTED] Task without title.
[SUCCESS] Task without title.
[246:0617/202810.971362:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 400: Permission denied (13)

DevTools listening on ws://127.0.0.1:45567/devtools/browser/66d04f2a-369e-4a49-a70b-3f4a981cd87d

====================================================================================================

  (Run Starting)

[246:0617/202811.867979:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 554: Permission denied (13)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        13.11.0                                                                        │
  │ Browser:        Electron 118 (headless)                                                        │
  │ Node Version:   v20.14.0 (/usr/local/bin/node)                                                 │
  │ Specs:          1 found (hotrod.cy.js)                                                         │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  │ Experiments:    experimentalStudio=true                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  hotrod.cy.js                                                                    (1 of 1)


  hotrod spec
    ✓ request ride (2282ms)


  1 passing (4s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     3 seconds                                                                        │
  │ Spec Ran:     hotrod.cy.js                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Video output: /root/hotrod/cypress/videos/hotrod.cy.js.mp4


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  hotrod.cy.js                             00:03        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:03        1        1        -        -        -  

```

### CODE REVIEW

**Review by davixcky — APPROVED** [review]
LGTM,

Q: why do we need to force the push?

**Comment by daniel-de-vera** [comment]
> Q: why do we need to force the push?

E.g. for pushing the `latest` tag (that gets moved from one commit to another).

**Comment by foxish** [comment]
I think we should have some default so it can verify the results without using the `_SANDBOX_NAME` parameters which seem to be clunky and hard to pass around - perhaps we can stick with the test only testing the output and not whether it prints the sandbox itself? The test that checks if it prints the sandbox itself makes sense for e2e but not for our demo scenarios.

**Comment by daniel-de-vera** [comment]
> I think we should have some default so it can verify the results without using the `_SANDBOX_NAME` parameters which seem to be clunky and noisy to pass around

Well, in fact the cypress tests have default values (empty), for example, locally you can run something like this:

```
hotrod $ CYPRESS_HOTROD_NAMESPACE=hotrod-devmesh npx cypress run
...                                                                                                   
  Running:  hotrod.cy.js                                                                    (1 of 1)

  hotrod spec
    ✓ request ride (2426ms)

  1 passing (5s)
...
```

The one lacking support for default values is our templating system.

> perhaps we can stick with the test only testing the output and not whether it prints the sandbox itself? The test that checks if it prints the sandbox itself makes sense for e2e but not for our demo scenarios.

I made some changes in the tests and created a new job template for demo purposes:

```bash
# For demo:
signadot job submit -f .signadot/testing/demo-tests-job.yaml --set branch=update-cypress-test --set namespace=hotrod-devmesh --set sandbox= --attach

# For e2e:
signadot job submit -f .signadot/testing/e2e-tests-job.yaml --set branch=update-cypress-test --set namespace=hotrod-devmesh --set sandbox=driver-sdx --set sandboxed_frontend=0 --set sandboxed_location=0 --set sandboxed_route=0 --set sandboxed_driver=1 --attach
```

@foxish, wdyt now?

**Comment by foxish** [comment]
It's better @daniel-de-vera but I feel like it's perhaps better to have the test not itself refer in any way to sandboxes - because that'll help keep the demo clear. In this case, the sandbox is being used within the app, which creates a confusing relationship. It makes sense for e2e, but perhaps there can be a separate test definition for the demo case in which the test is not aware of sandbox-related concepts.

**Comment by daniel-de-vera** [comment]
@foxish, I split the tests into two specs, one for demo, and another for e2e.

**Review by foxish — APPROVED** [review]
LGTM

**Pull request merged**
