### PR TITLE
move from templ to react app

### PR DESCRIPTION
**Pull request by davixcky**
- add react app
- serve react app

https://github.com/signadot/hotrod/assets/34346877/2cf3d24f-3c2c-460b-8e23-bf0dd360dcc9

### CODE REVIEW

**Comment by daniel-de-vera** [comment]
@davixcky , the page title is wrong:

Screenshot from 2024-03-08 12-21-54

**Comment by daniel-de-vera** [comment]
I guess when you request a driver, the notification accordion should open by default

**Comment by daniel-de-vera** [comment]
Here is a bug:

[screen-capture (15).webm](https://github.com/signadot/hotrod/assets/118383315/399a5849-27e2-4d53-80ce-66b815a176e1)

**Comment by davixcky** [comment]
@daniel-de-vera all comments has been addressed

**Comment by daniel-de-vera** [comment]
@davixcky, from what I understand we are not using:

- `services/frontend/static/*`
- `services/frontend/templates/*`

Can we remove those things? (to keep the code clean)

**Review by daniel-de-vera — APPROVED** [review]
LGTM, although I would wait for @foxish approval to merge it.

**Comment by foxish** [comment]
Is the sandbox preview for this working? I couldn't get it to happen on http://frontend.hotrod-istio.svc:8080/ with the header

**Comment by foxish** [comment]
LGTM, thanks!

**Pull request merged**
